name: Deploy mca-job-platform-

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production 
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        # Added working-directory to find the package.json
        run: npm install
        working-directory: ./mca-job-platform

      - name: Build Project
        run: npm run build
        working-directory: ./mca-job-platform

      - name: Admin Approval Notification
        run: echo "Build successful. Waiting for Admin (Abankwah4543) to approve the medical platform release..."
